model:
  package: twitch
  filename: ./twitch/models_gen.go
client:
  package: twitch
  filename: ./twitch/client.go
models:
  ID:
    model: github.com/99designs/gqlgen/graphql.ID
endpoint:
  url: https://api.twitch.tv/gql
  headers:
    Client-Id: "${TWITCH_CLIENT_ID}"
query:
  - "./query/*.graphql"
